function [spike, LFP, names] = autoDetectChannels(parsedFolderName)
% Function which takes in a parsed directory and returns the desired
% vectors for use in processRun.

assert(exist(parsedFolderName,'dir') == 7, 'parsed directory not found, parse then set autoDetect')

channelFiles = dir(fullfile(parsedFolderName, 'times_*'));
channelNums = extractBetween({channelFiles.name}, 'NSX_', '.mat');
channelNums = sort(str2double(channelNums));

% spikeChannels and lfpChannels must be the same length, in the same order, if analyzing both
% selTable Struct generated by runAnalyses relies on these vectors being in
% the correct order (1... N).
[spike, LFP] = deal(channelNums); 
names = cellstr(strcat('Ch', string(channelNums)));

end