function figh = plot_per_label_accuracy_curve(analysisBatch, analysisStruct, params)
% a function which generates a plot containing:
% - single trace per label used in the decoder
% - a mean trace of the overall accuracy
% - vertical lines at important events (denoted below)
% - Relabels X-axis (with numbers below).
% Inputs are
% - decoding_results, ds generated by neural decoding toolbox
% - analysisStruct, generated by k_aid scripts.

% Load the outputs from these analysisStructs
analysisOutputStructs = cellfun(@(x) load(x), analysisBatch);
analysisOutputStructs = [analysisOutputStructs.analysisStruct];
unitCountVec = [analysisOutputStructs.unitCount]';
decodingResultsStructs = {analysisOutputStructs.decoding_results_file}';
decodingResultsStructs = cellfun(@(x) load(x), decodingResultsStructs);
decodingResultsStructs = [decodingResultsStructs.decoding_results];

% Extract clear variables from inputs.
if length(decodingResultsStructs) ~= 1
  decoding_results_tmp = decodingResultsStructs(1);
else
  decoding_results_tmp = decodingResultsStructs;
end

decoding_type = 'Zero';
  switch decoding_type
    case 'Zero'
      decoding_data = [decodingResultsStructs.ZERO_ONE_LOSS_RESULTS];
    case 'Normalized'
      decoding_data = [decodingResultsStructs.NORMALIZED_RANK_RESULTS];
    case 'ROC_AUC'
      decoding_data = [decodingResultsStructs.ROC_AUC_RESULTS];
  end

uniqueUnitCounts = unique(unitCountVec);
[stdValPerVec, maxValPerVec] = deal(nan(size(uniqueUnitCounts)));

for count_i = 1:length(uniqueUnitCounts)
  % Identify runs with this unit count
  unitCountInd = unitCountVec == uniqueUnitCounts(count_i);
  
  % extract across all the scrambles and take the mean
  decoding_data_unitCount = decoding_data(unitCountInd);
  decoding_mean_results = cat(3, decoding_data_unitCount.mean_decoding_results);
  decoding_mean_results = mean(decoding_mean_results, 3);
  
  tmpstd = [decoding_data_unitCount.stdev];
  decoding_std_results = cat(3, tmpstd.over_CVs_combined_over_resamples);
  decoding_std_results = mean(decoding_std_results, 3);
  
  if size(decoding_mean_results,1) == size(decoding_mean_results,2)
    diagInd = logical(eye(size(decoding_mean_results)));    
  else
    diagInd = true(size(decoding_mean_results));    
  end
  
  meanDecodingResult = decoding_mean_results(diagInd);
  stdDecodingResult = decoding_std_results(diagInd);
  
  [maxValPerVec(count_i), maxInd] = max(meanDecodingResult);
  stdValPerVec(count_i) = stdDecodingResult(maxInd);
  
end

% plot
figure()
plot(maxValPerVec)
xticks(1:length(uniqueUnitCounts))
xticklabels(uniqueUnitCounts)
title('Peak response Across 10 Random Samples of X Units');
xlabel('Unit Number')
ylabel('Peak Decoding Accuracy');
  
saveFigure(analysisStruct.plotOutDir, sprintf('1. %s - %s - Cumulative Curve', analysisStruct.plotTitle), [], params.figStruct, [])